# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'test_pipeline'
    subscriptionId: '01260f03-1715-40be-8394-c933c13729e3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test_pipline_rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/stat-ml/SPOC/compatibility_2021/azure_templates/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    overrideParameters: '-projectName spoc'
